// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxTMEVRFRhpYIPHeAiRpo6R9hxV6-364',
    appId: '1:320357754373:web:4f55b3bb9e90bcb45c5e6c',
    messagingSenderId: '320357754373',
    projectId: 'ecommerce-catalog-app',
    authDomain: 'ecommerce-catalog-app.firebaseapp.com',
    storageBucket: 'ecommerce-catalog-app.firebasestorage.app',
    measurementId: 'G-SYWDCP1ELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifox5-4Mprp9wss6Xo4n96Abw-rKG8dI',
    appId: '1:320357754373:android:a6932279fc10fcdc5c5e6c',
    messagingSenderId: '320357754373',
    projectId: 'ecommerce-catalog-app',
    storageBucket: 'ecommerce-catalog-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgNPfP4dBz9BIy6wETm45dBUbAoXTuzks',
    appId: '1:320357754373:ios:179dc78a761b3c935c5e6c',
    messagingSenderId: '320357754373',
    projectId: 'ecommerce-catalog-app',
    storageBucket: 'ecommerce-catalog-app.firebasestorage.app',
    iosBundleId: 'com.example.iti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgNPfP4dBz9BIy6wETm45dBUbAoXTuzks',
    appId: '1:320357754373:ios:179dc78a761b3c935c5e6c',
    messagingSenderId: '320357754373',
    projectId: 'ecommerce-catalog-app',
    storageBucket: 'ecommerce-catalog-app.firebasestorage.app',
    iosBundleId: 'com.example.iti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxTMEVRFRhpYIPHeAiRpo6R9hxV6-364',
    appId: '1:320357754373:web:f54b8f5c1c1ce8b25c5e6c',
    messagingSenderId: '320357754373',
    projectId: 'ecommerce-catalog-app',
    authDomain: 'ecommerce-catalog-app.firebaseapp.com',
    storageBucket: 'ecommerce-catalog-app.firebasestorage.app',
    measurementId: 'G-6RTFH6SHEW',
  );
}
